Logging argparsing
DataWaveProject/nonlocal_gwfluxes pull request #34
Opened 2024-12-18 08:58 UTC by amangupta2

#28 

-- Built on branch ablation_10layers
-- Replaced all print statements with logger.info
-- And now parsing command line arguments using argparse. Agreed, it is much neater and convenient.

If all looks good, we can merge this with ablation 10_layers and merge that with main.

2025-01-16 13:44 UTC, TomMelt requested changes
Thanks @amangupta2 , these changes will greatly improve the scripts and make them easier to run and more robust.

The argparse now adds additional sanity checks to your inputs which will help prevent user error. Great job :+1: 

I have made a couple of suggestions. We can discuss them in the next meeting if you prefer.

2025-01-16 13:44 UTC, TomMelt commented on ann_cnn_training/inference_ifs.py
> +parser = argparse.ArgumentParser()
similar changes here to argparse as before for `ann_cnn_training/inference.py`

2025-01-16 13:44 UTC, TomMelt commented on ann_cnn_training/training.py
> +parser.add_argument("-i", "--input_dir", default=".", help="Input directory with training data")
similar changes here to argparse as before for `ann_cnn_training/inference.py`

2025-01-16 13:44 UTC, TomMelt commented on attention_unet/inference.py
> +    choices=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
similar changes here to argparse as before for `ann_cnn_training/inference.py`

2025-01-16 13:44 UTC, TomMelt commented on attention_unet/training_attention_unet.py
> +parser.add_argument(
similar changes here to argparse as before for `ann_cnn_training/inference.py`

2025-01-16 13:44 UTC, TomMelt commented on ifs_transfer_learning/ANN_inference.py
> +    choices=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
similar changes here to argparse as before for `ann_cnn_training/inference.py`

2025-01-16 13:44 UTC, TomMelt commented on ifs_transfer_learning/attn_inference.py
> +    choices=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
similar changes here to argparse as before for `ann_cnn_training/inference.py`

2025-01-16 13:44 UTC, TomMelt commented on ifs_transfer_learning/training_ifs_transfer_learning.py
> +parser.add_argument(
similar changes here to argparse as before for `ann_cnn_training/inference.py`

2025-01-16 13:44 UTC, TomMelt commented on quick_inference_script/two_sample_inference.py
> +
```suggestion
```

best practice to remove unused code rather than "commenting" it out. We can always go back to an earlier version (through git/GitHib) if we need it again.

2025-01-16 13:44 UTC, TomMelt commented on quick_inference_script/two_sample_inference.py
> +    # )
same here. We can either delete it, or move it to the `logger`

2025-01-16 13:44 UTC, TomMelt commented on quick_inference_script/two_sample_inference.py
> +    # )
and here

2025-01-23 07:12 UTC, amangupta2 commented on ann_cnn_training/function_training.py
> +    model, testset, testloader, bs_test, device, stencil, logger, outfile
@TomMelt 

I updated the logger implementation, however, my logger needs an input file name to write to which is defined in __main__. How can we export this filename from era5_training/training.py to utils/function_training.py?

![image](https://github.com/user-attachments/assets/425c5ccd-06f4-4e5d-930c-edc4d7ce43a3)

2025-01-23 10:17 UTC, TomMelt commented on ann_cnn_training/function_training.py
> +    model, testset, testloader, bs_test, device, stencil, logger, outfile
The trick is you don't need to set the `basicConfig` everywhere i.e.,

```python
logging.basicConfig(filename=log_filename, level=logging.INFO)
```

You just do it once and then when you initialize logger in the other files they can inherit the information from the parent logger.

By manually setting `logging.basicConfig(filename=log_filename, level=logging.INFO)` in each file you are over-writing the parent logger.

2025-02-05 16:41 UTC, TomMelt commented
this was superseded by #37

2025-02-05 16:41 UTC, closed without merging